name = "aniflixx-analytics"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
account_id = "36be7c1a54d196cbf30e4b923fb82fb8"

[[env.production.analytics_engine_datasets]]
binding = "STUDIO_ANALYTICS"

[[env.production.analytics_engine_datasets]]
binding = "USER_BEHAVIOR"  

[[env.production.analytics_engine_datasets]]
binding = "REVENUE_TRACKING"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "eb461eea89d04d498c69d5504e248e87"

[env.production.vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"
ACCOUNT_ID = "36be7c1a54d196cbf30e4b923fb82fb8"

[vars]
ANALYTICS_API_TOKEN = "9jBx8QIQzqQTQSvKnd5HbILCPnim1Csu3BbYMeTB"